name: Build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive Latest Calendar
        uses: actions/upload-artifact@v4
        with:
          name: personal-website-artifact
          path: |
            build
  deploy-s3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: personal-website-artifact
          path: build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Deploy
        run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }}
      - name: Invalidate Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRUBUTION_ID }} --paths "/*"
  deploy-github-page:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
      - name: Clone Repo
        run: |
          git clone https://atomyyyy:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/atomyyyy/atomyyyy.github.io.git
          cd atomyyyy.github.io
          git fetch origin gh-pages
          git checkout gh-pages
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: personal-website-artifact
          path: atomyyyy.github.io
      - name: Push Change
        run: |
          cd atomyyyy.github.io
          git add --all
          git commit -m "chore: update personal page"
          git push origin gh-pages
